In [ ]:
import pandas as pd

In [ ]:
tuples = [("A", 1), ("A", 2), ("B", 1), ("B", 2)]
index = pd.MultiIndex.from_tuples(tuples, names=["Letter", "Number"])

In [ ]:
arrays = [["A", "A", "B", "B"], [1, 2, 1, 2]]
index_from_arrays = pd.MultiIndex.from_arrays(arrays, names=["Letter", "Number"])

In [ ]:
index_from_product = pd.MultiIndex.from_product([['A', 'B'], [1, 2]], names=["Letter", "Number"])

In [ ]:
s = pd.Series([10, 20, 30, 40], index=index)
print("Series with MultiIndex:\n", s)

Series with MultiIndex:
 Letter  Number
A       1         10
        2         20
B       1         30
        2         40
dtype: int64

In [ ]:
# 5. DataFrame with MultiIndex
columns = pd.MultiIndex.from_product([['Math', 'Science'], ['Mid', 'Final']])
df = pd.DataFrame([[50, 60, 70, 80], [90, 85, 75, 95]], index=["Student1", "Student2"], columns=columns)
print("\nDataFrame with MultiIndex columns:\n", df)

DataFrame with MultiIndex columns:
          Math       Science
          Mid Final     Mid Final
Student1   50    60      70    80
Student2   90    85      75    95

In [ ]:
# 6. Accessing Index and Columns
print("\nIndex Levels:", df.index)
print("\nColumn Levels:", df.columns)

Index Levels: Index(['Student1', 'Student2'], dtype='object')

Column Levels: MultiIndex([(   'Math',   'Mid'),
            (   'Math', 'Final'),
            ('Science',   'Mid'),
            ('Science', 'Final')],
           )

In [ ]:
print("\nUsing loc for specific value:\n", s.loc["A", 1])

Using loc for specific value:
 10

In [ ]:
print("\nUsing xs for level access:\n", s.xs("A"))

Using xs for level access:
 Number
1    10
2    20
dtype: int64

In [ ]:
# 9. swaplevel()
swapped = s.swaplevel()
print("\nSwapped Levels:\n", swapped)

Swapped Levels:
 Number  Letter
1       A         10
2       A         20
1       B         30
2       B         40
dtype: int64

In [ ]:
# 10. sort_index()
sorted_index = s.sort_index()
print("\nSorted Index:\n", sorted_index)

Sorted Index:
 Letter  Number
A       1         10
        2         20
B       1         30
        2         40
dtype: int64

In [ ]:
# 11. sort_index(level=)
sorted_level = s.sort_index(level=1)
print("\nSorted by Level=1:\n", sorted_level)

Sorted by Level=1:
 Letter  Number
A       1         10
B       1         30
A       2         20
B       2         40
dtype: int64

In [ ]:
# 12. unstack()
unstacked = s.unstack()
print("\nUnstacked Series:\n", unstacked)

Unstacked Series:
 Number   1   2
Letter
A       10  20
B       30  40

In [ ]:
# 13. stack()
stacked = unstacked.stack()
print("\nRestacked Series:\n", stacked)

Restacked Series:
 Letter  Number
A       1         10
        2         20
B       1         30
        2         40
dtype: int64

In [ ]:
# 14. transpose()
print("\nTransposed DataFrame:\n", df.T)

Transposed DataFrame:
                Student1  Student2
Math    Mid          50        90
        Final        60        85
Science Mid          70        75
        Final        80        95

In [ ]:
# 15. melt()
df_reset = df.reset_index()
melted = pd.melt(df_reset, id_vars=["Student1"], var_name=["Subject", "Exam"], value_name="Score")
print("\nMelted DataFrame:\n", melted)

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Student1']"