In [2]:
import pandas as pd
import numpy as np

In [3]:
# Replace 'blob' with 'raw' in the URL to access the raw file content
url = 'https://raw.githubusercontent.com/sawlachintan/cricket_data/main/data/bronze/bbl/innings_df.csv'
# Removed '/raw' from the URL path as it's redundant when using 'raw.githubusercontent.com'
df = pd.read_csv(url, on_bad_lines='skip', delimiter=',')
df.head(10)

<ipython-input-3-a31872959f0c>:4: DtypeWarning: Columns (16,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url, on_bad_lines='skip', delimiter=',')

,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,over,delivery_no,batting_team,inning_no,...,key,runs_non_boundary,replacements_match,review_by,review_umpire,review_batter,review_decision,review_umpires_call,review_type,extras_type
0,BB McCullum,B Lee,ML Hayden,0,0,0,0,1,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BB McCullum,B Lee,ML Hayden,0,0,0,0,2,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BB McCullum,B Lee,ML Hayden,4,0,4,0,3,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BB McCullum,B Lee,ML Hayden,0,0,0,0,4,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BB McCullum,B Lee,ML Hayden,0,0,0,0,5,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,BB McCullum,B Lee,ML Hayden,0,0,0,0,6,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ML Hayden,MA Starc,BB McCullum,0,0,0,1,1,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ML Hayden,MA Starc,BB McCullum,0,0,0,1,2,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ML Hayden,MA Starc,BB McCullum,4,0,4,1,3,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,ML Hayden,MA Starc,BB McCullum,4,0,4,1,4,Brisbane Heat,1,...,bbl00001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['batter', 'bowler', 'non_striker', 'runs_batter', 'runs_extras',
       'runs_total', 'over', 'delivery_no', 'batting_team', 'inning_no',
       'replacements_role', 'wickets_kind', 'wickets_player_out',
       'bowling_team', 'key', 'runs_non_boundary', 'replacements_match',
       'review_by', 'review_umpire', 'review_batter', 'review_decision',
       'review_umpires_call', 'review_type', 'extras_type'],
      dtype='object')

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/itsmecevi/dataset/main/pakistan_intellectual_capital.csv')
df

,Unnamed: 0,S#,Teacher Name,University Currently Teaching,Department,Province University Located,Designation,Terminal Degree,Graduated from,Country,Year,Area of Specialization/Research Interests,Other Information
0,2,3,Dr. Abdul Basit,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,Software Engineering & DBMS,NaN
1,4,5,Dr. Waheed Noor,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,DBMS,NaN
2,5,6,Dr. Junaid Baber,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"Information processing, Multimedia mining",NaN
3,6,7,Dr. Maheen Bakhtyar,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"NLP, Information Retrieval, Question Answering...",NaN
4,24,25,Samina Azim,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Balochistan University of Information Technolo...,Pakistan,2005.0,VLSI Electronics DLD Database,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137,1974,1975,Dr. Ahmar Rashid,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Associate Professor,PhD,JNU,South Korea,NaN,"Electrical Impedance Tomography, Inverse algor...",NaN
1138,1975,1976,Dr. Fawad Hussain,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Associate Professor,PhD,Grenoble,France,NaN,"Machine Learning, Big Data Anaysis, Data Minin...",NaN
1139,1977,1978,Dr. Rashad M Jillani,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Florida Atlantic University,USA,2012.0,"Digital Multimedia Systems, Video Compression ...",NaN
1140,1979,1980,Dr. Shahabuddin Ansari,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Ghulam Ishaq Khan Institute of Science and Tec...,Pakistan,NaN,"Medical Image Processing and Analysis, Digital...",NaN
1141,1980,1981,Dr. Sajid Anwar,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Seoul National University,South Korea,NaN,"Pruning and Quantizing CNN, GPGPU,",NaN

In [6]:
df.head()

,Unnamed: 0,S#,Teacher Name,University Currently Teaching,Department,Province University Located,Designation,Terminal Degree,Graduated from,Country,Year,Area of Specialization/Research Interests,Other Information
0,2,3,Dr. Abdul Basit,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,Software Engineering & DBMS,NaN
1,4,5,Dr. Waheed Noor,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,DBMS,NaN
2,5,6,Dr. Junaid Baber,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"Information processing, Multimedia mining",NaN
3,6,7,Dr. Maheen Bakhtyar,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"NLP, Information Retrieval, Question Answering...",NaN
4,24,25,Samina Azim,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Balochistan University of Information Technolo...,Pakistan,2005.0,VLSI Electronics DLD Database,NaN

In [7]:
# General info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1142 entries, 0 to 1141
Data columns (total 13 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Unnamed: 0                                 1142 non-null   int64
 1   S#                                         1142 non-null   int64
 2   Teacher Name                               1142 non-null   object
 3   University Currently Teaching              1142 non-null   object
 4   Department                                 1142 non-null   object
 5   Province University Located                1142 non-null   object
 6   Designation                                1123 non-null   object
 7   Terminal Degree                            1138 non-null   object
 8   Graduated from                             1142 non-null   object
 9   Country                                    1142 non-null   object
 10  Year                                       489 non-null    float64
 11  Area of Specialization/Research Interests  623 non-null    object
 12  Other Information                          124 non-null    object
dtypes: float64(1), int64(2), object(10)
memory usage: 116.1+ KB

In [8]:
# statistical summary for numeric columns
df.describe()

        Unnamed: 0           S#         Year
count  1142.000000  1142.000000   489.000000
mean   1054.350263  1055.350263  2010.456033
std     520.202783   520.202783     5.577565
min       2.000000     3.000000  1983.000000
25%     689.250000   690.250000  2008.000000
50%    1087.500000  1088.500000  2012.000000
75%    1476.750000  1477.750000  2014.000000
max    1980.000000  1981.000000  2018.000000

In [9]:
# check for the null values
df.isnull().sum()

Unnamed: 0                                      0
S#                                              0
Teacher Name                                    0
University Currently Teaching                   0
Department                                      0
Province University Located                     0
Designation                                    19
Terminal Degree                                 4
Graduated from                                  0
Country                                         0
Year                                          653
Area of Specialization/Research Interests     519
Other Information                            1018
dtype: int64

In [10]:
# identifying unique and Duplicate Values

# count unique values in each column
df.nunique()

# check for the duplicated in each rows
df.duplicated().sum()

0

In [11]:
df.nunique()

Unnamed: 0                                   1142
S#                                           1142
Teacher Name                                 1133
University Currently Teaching                  63
Department                                     17
Province University Located                     5
Designation                                    46
Terminal Degree                                42
Graduated from                                350
Country                                        38
Year                                           32
Area of Specialization/Research Interests     571
Other Information                              52
dtype: int64

In [12]:
df['Teacher Name'].value_counts().head()

Teacher Name
Muhammad Zubair    3
Naila Shah         2
Muhammad Nauman    2
Naveed Ahmad       2
Mehdi Hassan       2
Name: count, dtype: int64

In [13]:
df['Department'].value_counts()

Department
Computer Science                               744
Computer Engineering                            81
Information Technology                          62
Computing                                       43
Computer Science & IT                           41
Computing & Information Sciences                38
Institute of Mathematics & Computer Science     25
FACULTY OF COMPUTING & ENGINEERING              22
Computer Science and Software Engineering       21
Computer and Information Sciences               19
CS & IT                                         14
School of Information and Technology            11
ENGINEERING, SCIENCE & TECHNOLOGY                7
Computer Science and Engineering                 6
Computer Science and IT                          4
Software Engineering                             2
Computer Sciences                                2
Name: count, dtype: int64

In [14]:
df.columns

Index(['Unnamed: 0', 'S#', 'Teacher Name', 'University Currently Teaching',
       'Department', 'Province University Located', 'Designation',
       'Terminal Degree', 'Graduated from', 'Country', 'Year',
       'Area of Specialization/Research Interests', 'Other Information'],
      dtype='object')

In [15]:
df.sort_values('Teacher Name' , ascending = False )

,Unnamed: 0,S#,Teacher Name,University Currently Teaching,Department,Province University Located,Designation,Terminal Degree,Graduated from,Country,Year,Area of Specialization/Research Interests,Other Information
912,1537,1538,Syed Nabeel Ali,PAF-Karachi Institute of Economics and Technology,Computing & Information Sciences,Sindh,Lecturer,MS,NED University of Engineering And Technology,Pakistan,NaN,NaN,NaN
482,971,972,Sobia Tariq Javed,FAST(Lahore),Computer Science,Punjab,Assistant Professor,MS,FAST– National University of Computer and Emer...,Pakistan,2007.0,"computer vision, image processing, Script proc...",NaN
878,1499,1500,Ms. Kainat,Jinnah University for Women,Computer Science & IT,Sindh,Lecturer,BS,Jinnah University for Women,Pakistan,NaN,NaN,NaN
873,1494,1495,Ms. Humaira Meraj,Jinnah University for Women,Computer Science & IT,Sindh,Lecturer,MS,Sir Syed University of Engineering and Technology,Pakistan,NaN,NaN,NaN
880,1504,1505,Hironao Takahashi,DHA Suffa University,Computer Science,Sindh,Associate Professor,PhD,Tokyo Institute of Technology,Japan,NaN,Ontology-based Classification and Mind Uploading,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
840,1446,1447,ABEER JAVED SYED,Sir Syed University of Engineering and Technology,Computer Engineering,Sindh,Lecturer,MS,Hamdard University,Pakistan,NaN,NaN,NaN
649,1232,1233,ABDUL SATTAR SOOMRO,University of Sindh,Institute of Mathematics & Computer Science,Sindh,Professor,Post Doc,"Griffith University,Nathan Campus",Australia,2005.0,NaN,NaN
148,365,366,ABDUL KALEEM,National University of Modern Languages,Computer Science,Capital,Lecturer,BS,National University of Modern Languages,Pakistan,2005.0,"Artificial Intelligence, Programming, algorith...",NaN
1035,1728,1729,Naveed Ahmad Khan Jhamat,"Punjab University,Gujranwala Campus",Computer Science,Punjab,Assistant Professor,MSc,University of the Punjab,Pakistan,NaN,NaN,On study leave
122,314,315,Dr. Ali Daud,"International Islamic University,Islamabad",Computer Science and Software Engineering,Capital,Associate Professor,PhD,Tsinghua University,China,2010.0,"Text Mining,Information Retrieval, Information...",NaN

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/shishir349/Analyzing-the-IMDB-Movie-Dataset/refs/heads/master/movie_metadata.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [17]:
movies = pd.read_csv('https://raw.githubusercontent.com/LearnDataSci/articles/refs/heads/master/Python%20Pandas%20Tutorial%20A%20Complete%20Introduction%20for%20Beginners/IMDB-Movie-Data.csv')
movies

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [18]:
movies.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [19]:
movies.reset_index()

,index,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [20]:
movies.rename(columns = {'Title' : 'title' , 'Year' : 'year_of_release'})

,Rank,title,Genre,Description,Director,Actors,year_of_release,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [21]:
movies['Year'].notnull()

0      True
1      True
2      True
3      True
4      True
       ...
995    True
996    True
997    True
998    True
999    True
Name: Year, Length: 1000, dtype: bool

In [22]:
movies.isnull()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,True,False
996,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,True,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [23]:
movies.notnull()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,True,True,True,True,True,True,True,True,True,True,False,True
996,True,True,True,True,True,True,True,True,True,True,True,True
997,True,True,True,True,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True,True,True,False,True
999,True,True,True,True,True,True,True,True,True,True,True,True

In [24]:
movies['Title'].dropna(how='all')

0      Guardians of the Galaxy
1                   Prometheus
2                        Split
3                         Sing
4                Suicide Squad
                ...
995       Secret in Their Eyes
996            Hostel: Part II
997     Step Up 2: The Streets
998               Search Party
999                 Nine Lives
Name: Title, Length: 1000, dtype: object

In [26]:
movies.dropna(subset = ['Title'])

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [28]:
movies.groupby('Year').sum()

,Rank,Title,Genre,Description,Director,Actors,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Year,,,,,,,,,,,
2006,25894,The PrestigePirates of the Caribbean: Dead Man...,"Drama,Mystery,Sci-FiAction,Adventure,FantasyCr...",Two stage magicians engage in competitive one-...,Christopher NolanGore VerbinskiMartin Scorsese...,"Christian Bale, Hugh Jackman, Scarlett Johanss...",5317,313.5,11848758,3624.46,2641.0
2007,30559,5- 25- 77Pirates of the Caribbean: At World's ...,"Comedy,DramaAction,Adventure,FantasyCrime,Dram...","Alienated, hopeful-filmmaker Pat Johnson's epi...",Patrick Read JohnsonGore VerbinskiEthan CoenGr...,"John Francis Daley, Austin Pendleton, Colleen ...",6446,378.1,12949545,4306.23,2967.0
2008,32533,The Dark KnightMamma Mia!TwilightTropic Thunde...,"Action,Crime,DramaComedy,Family,MusicalDrama,F...",When the menace known as the Joker wreaks havo...,Christopher NolanPhyllida LloydCatherine Hardw...,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",5763,352.8,14326280,5053.22,2813.0
2009,29928,Inglourious BasterdsAvatarStar TrekWatchmenKyn...,"Adventure,Drama,WarAction,Adventure,FantasyAct...","In Nazi-occupied France during World War II, a...",Quentin TarantinoJames CameronJ.J. AbramsZack ...,"Brad Pitt, Diane Kruger, Eli Roth,Mélanie Laur...",5922,355.0,13044813,5292.26,2799.0
2010,35239,InceptionShutter IslandDiary of a Wimpy KidSco...,"Action,Adventure,Sci-FiMystery,ThrillerComedy,...","A thief, who steals corporate secrets through ...",Christopher NolanMartin ScorseseThor Freudenth...,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",6668,409.6,15166939,5989.65,3504.0
2011,37143,Pirates of the Caribbean: On Stranger TidesThe...,"Action,Adventure,FantasyDramaAction,Adventure,...",Jack Sparrow and Barbossa embark on a quest to...,Rob MarshallTate TaylorKenneth BranaghDavid Ya...,"Johnny Depp, Penélope Cruz, Ian McShane, Geoff...",7220,430.8,15169789,5431.96,3580.0
2012,34104,PrometheusThe AvengersThe Dark Knight RisesThe...,"Adventure,Mystery,Sci-FiAction,Sci-FiAction,Th...","Following clues to the origin of mankind, a te...",Ridley ScottJoss WhedonChristopher NolanDerek ...,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",7623,443.2,18254470,6910.29,3791.0
2013,50617,The Wolf of Wall StreetPrisoners12 Years a Sla...,"Biography,Comedy,CrimeCrime,Drama,MysteryBiogr...","Based on the true story of Jordan Belfort, fro...",Martin ScorseseDenis VilleneuveSteve McQueenJu...,"Leonardo DiCaprio, Jonah Hill, Margot Robbie,M...",10562,619.9,19933518,7666.72,5034.0
2014,50272,Guardians of the GalaxyInterstellarJohn WickKi...,"Action,Adventure,Sci-FiAdventure,Drama,Sci-FiA...",A group of intergalactic criminals are forced ...,James GunnChristopher NolanChad StahelskiMatth...,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",11220,670.1,19985162,7997.40,5445.0
2015,62407,Bahubali: The BeginningStar Wars: Episode VII ...,"Action,Adventure,DramaAction,Adventure,Fantasy...","In ancient India, an adventurous and daring ma...",S.S. RajamouliJ.J. AbramsSam Taylor-JohnsonGeo...,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",14541,838.5,14697230,8854.12,7016.0
2016,111804,SplitSingSuicide SquadThe Great WallLa La Land...,"Horror,ThrillerAnimation,Comedy,FamilyAction,A...",Three girls are kidnapped by a man with a diag...,M. Night ShyamalanChristophe LourdeletDavid Ay...,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",31890,1911.7,14431751,11211.65,15620.0